services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - FACTION_DB_LOCATION=postgres://factionreadwrite:readwrite@postgres:5432/faction?sslmode=disable
      - FACTION_REDIS_LOCATION=redis:6379
      - ENABLE_DEBUG=true
      - ENABLE_LOCAL_MODE=false
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 3
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  asynqmon:
    image: "hibiken/asynqmon"
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
#  opensearch:
#    image: "opensearchproject/opensearch:latest"
#    ports:
#      - "9200:9200"
#  dashboards:
#    image: "opensearchproject/opensearch-dashboards:latest"
#    ports:
#      - "5601:8082"
