services:
  # Faction worker process(es)
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["worker"]
    environment:
      - POSTGRES_PASSWORD=test
      - DATABASE_DRIVER=postgres
      - DATABASE_URL=postgres://postgres:test@postgres:5432/faction?sslmode=disable
      - QUEUE_DRIVER=igor
      - QUEUE_URL=redis:6379
      - QUEUE_DATABASE_URL=postgres://postgres:test@postgres:5432/igor?sslmode=disable
      - ENABLE_DEBUG=true
      - ENABLE_LOCAL_MODE=false
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 3

  # SERVICES
  igor-api:  # igor's API Server
    image: "uristmcdwarf/igor:0.0.5"
    command: ["api"]
    ports:
      - "8100:8100"
    environment:
      - DATABASE_URL=postgres://postgres:test@postgres:5432/igor?sslmode=disable
      - QUEUE_URL=redis:6379
      - ADDR=0.0.0.0:8100
      - DEBUG=true
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 1
  igor-internal: # igor's internal management process
    image: "uristmcdwarf/igor:0.0.5"
    command: ["worker"]
    environment:
      - DATABASE_URL=postgres://postgres:test@postgres:5432/igor?sslmode=disable
      - QUEUE_URL=redis:6379
      - DEBUG=true
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 1

  # INFRASTRUCTURE
  redis: # infrastructure: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  asynqmon:
    image: "hibiken/asynqmon"
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
  postgres: # infrastructure: postgres
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
#  opensearch:
#    image: "opensearchproject/opensearch:latest"
#    ports:
#      - "9200:9200"
#  dashboards:
#    image: "opensearchproject/opensearch-dashboards:latest"
#    ports:
#      - "5601:8082"
