services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - FACTION_DB_LOCATION=postgres://factionreadwrite:readwrite@postgres:5432/faction?sslmode=disable
      - FACTION_REDIS_LOCATION=redis:6379
    depends_on:
      - postgres
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  asynqmon:
    image: "hibiken/asynqmon"
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
  pgadmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - "8081:8081"
    environment:
      - PGADMIN_LISTEN_PORT=8081
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
        #  opensearch:
        # image: "opensearchproject/opensearch:latest"
        #ports:
        #- "9200:9200"
        #dashboards:
        #image: "opensearchproject/opensearch-dashboards:latest"
        #ports:
        #- "5601:8082"
