receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
extensions:
  pprof:
  health_check:
  zpages:
    endpoint: 0.0.0.0:55679
exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9090
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
