// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.6
// source: common.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metaref is a reference to a specific object in the world. The value depends on the key.
type Metaref struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Protobuf; why you no support string constants?
	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Metaref) Reset() {
	*x = Metaref{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metaref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metaref) ProtoMessage() {}

func (x *Metaref) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metaref.ProtoReflect.Descriptor instead.
func (*Metaref) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Metaref) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metaref) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Distribution represents a normal distribution
type Distribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min       float64 `protobuf:"fixed64,1,opt,name=Min,proto3" json:"Min,omitempty"`
	Max       float64 `protobuf:"fixed64,2,opt,name=Max,proto3" json:"Max,omitempty"`
	Mean      float64 `protobuf:"fixed64,3,opt,name=Mean,proto3" json:"Mean,omitempty"`
	Deviation float64 `protobuf:"fixed64,4,opt,name=Deviation,proto3" json:"Deviation,omitempty"`
}

func (x *Distribution) Reset() {
	*x = Distribution{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution) ProtoMessage() {}

func (x *Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution.ProtoReflect.Descriptor instead.
func (*Distribution) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Distribution) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Distribution) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Distribution) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *Distribution) GetDeviation() float64 {
	if x != nil {
		return x.Deviation
	}
	return 0
}

// Select represents a search for matching objects
type Select struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Any map[string]string `protobuf:"bytes,1,rep,name=Any,proto3" json:"Any,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	All map[string]string `protobuf:"bytes,2,rep,name=All,proto3" json:"All,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Not map[string]string `protobuf:"bytes,3,rep,name=Not,proto3" json:"Not,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Select) Reset() {
	*x = Select{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Select) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Select) ProtoMessage() {}

func (x *Select) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Select.ProtoReflect.Descriptor instead.
func (*Select) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Select) GetAny() map[string]string {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *Select) GetAll() map[string]string {
	if x != nil {
		return x.All
	}
	return nil
}

func (x *Select) GetNot() map[string]string {
	if x != nil {
		return x.Not
	}
	return nil
}

// Feeling represents an entity might have toward another entity
// This is one directional.
type Feeling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Fear is a measure of how much the entity fears the other entity, fear is slow to change
	Fear *float64 `protobuf:"fixed64,1,opt,name=Fear,proto3,oneof" json:"Fear,omitempty"`
	// Opinion varies wildly, being swift to change based on events with it's effects more mild
	Opinion *float64 `protobuf:"fixed64,2,opt,name=Opinion,proto3,oneof" json:"Opinion,omitempty"`
	// Trust is a measure of how much the entity trusts the other entity, trust is slow to change &
	// with stronger long term effects
	Trust *float64 `protobuf:"fixed64,3,opt,name=Trust,proto3,oneof" json:"Trust,omitempty"`
	// Affiliation is a measure of how much the entity is affiliated with the other entity.
	Affiliation *float64 `protobuf:"fixed64,4,opt,name=Affiliation,proto3,oneof" json:"Affiliation,omitempty"`
}

func (x *Feeling) Reset() {
	*x = Feeling{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feeling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feeling) ProtoMessage() {}

func (x *Feeling) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feeling.ProtoReflect.Descriptor instead.
func (*Feeling) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Feeling) GetFear() float64 {
	if x != nil && x.Fear != nil {
		return *x.Fear
	}
	return 0
}

func (x *Feeling) GetOpinion() float64 {
	if x != nil && x.Opinion != nil {
		return *x.Opinion
	}
	return 0
}

func (x *Feeling) GetTrust() float64 {
	if x != nil && x.Trust != nil {
		return *x.Trust
	}
	return 0
}

func (x *Feeling) GetAffiliation() float64 {
	if x != nil && x.Affiliation != nil {
		return *x.Affiliation
	}
	return 0
}

// Thought is the combination of "Match" and "Feeling"
// Match => What / who I am thinking of
// Feeling => What I am feeling
type Thought struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Select  *Select  `protobuf:"bytes,2,opt,name=Select,proto3,oneof" json:"Select,omitempty"`
	Feeling *Feeling `protobuf:"bytes,3,opt,name=Feeling,proto3" json:"Feeling,omitempty"`
}

func (x *Thought) Reset() {
	*x = Thought{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thought) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thought) ProtoMessage() {}

func (x *Thought) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thought.ProtoReflect.Descriptor instead.
func (*Thought) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Thought) GetSelect() *Select {
	if x != nil {
		return x.Select
	}
	return nil
}

func (x *Thought) GetFeeling() *Feeling {
	if x != nil {
		return x.Feeling
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31,
	0x0a, 0x07, 0x4d, 0x65, 0x74, 0x61, 0x72, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x64, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x4d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x4d, 0x61, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x61, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x4d, 0x65, 0x61, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x76,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x44, 0x65,
	0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9c, 0x02, 0x0a, 0x06, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x12, 0x22, 0x0a, 0x03, 0x41, 0x6e, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x2e, 0x41, 0x6e, 0x79, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x03, 0x41, 0x6e, 0x79, 0x12, 0x22, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x2e, 0x41, 0x6c, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x41, 0x6c, 0x6c, 0x12, 0x22, 0x0a, 0x03, 0x4e, 0x6f,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x2e, 0x4e, 0x6f, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x4e, 0x6f, 0x74, 0x1a, 0x36,
	0x0a, 0x08, 0x41, 0x6e, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x36, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x36,
	0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb2, 0x01, 0x0a, 0x07, 0x46, 0x65, 0x65, 0x6c, 0x69,
	0x6e, 0x67, 0x12, 0x17, 0x0a, 0x04, 0x46, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x00, 0x52, 0x04, 0x46, 0x65, 0x61, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x4f,
	0x70, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x07,
	0x4f, 0x70, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x54, 0x72,
	0x75, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x05, 0x54, 0x72, 0x75,
	0x73, 0x74, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x41, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x03, 0x52, 0x0b, 0x41, 0x66,
	0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x46, 0x65, 0x61, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x4f, 0x70, 0x69, 0x6e, 0x69, 0x6f,
	0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x54, 0x72, 0x75, 0x73, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x41, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5e, 0x0a, 0x07, 0x54,
	0x68, 0x6f, 0x75, 0x67, 0x68, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x48,
	0x00, 0x52, 0x06, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x07,
	0x46, 0x65, 0x65, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x46, 0x65, 0x65, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x46, 0x65, 0x65, 0x6c, 0x69, 0x6e, 0x67,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x0d, 0x5a, 0x0b, 0x70,
	0x6b, 0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_proto_goTypes = []any{
	(*Metaref)(nil),      // 0: Metaref
	(*Distribution)(nil), // 1: Distribution
	(*Select)(nil),       // 2: Select
	(*Feeling)(nil),      // 3: Feeling
	(*Thought)(nil),      // 4: Thought
	nil,                  // 5: Select.AnyEntry
	nil,                  // 6: Select.AllEntry
	nil,                  // 7: Select.NotEntry
}
var file_common_proto_depIdxs = []int32{
	5, // 0: Select.Any:type_name -> Select.AnyEntry
	6, // 1: Select.All:type_name -> Select.AllEntry
	7, // 2: Select.Not:type_name -> Select.NotEntry
	2, // 3: Thought.Select:type_name -> Select
	3, // 4: Thought.Feeling:type_name -> Feeling
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[3].OneofWrappers = []any{}
	file_common_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
