// FILE IS AUTOGENERATED. DO NOT EDIT!
package structs

import (
    "google.golang.org/protobuf/encoding/protojson"
)

func (x *Affiliation) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Affiliation) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Faction) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Faction) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *FactionStatus) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *FactionStatus) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetFactionsRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetFactionsRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetFactionsResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetFactionsResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetFactionsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *SetFactionsRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetFactionsRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetFactionsResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetFactionsResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetFactionsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *DeleteFactionRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteFactionRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteFactionResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteFactionResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteFactionResponse) SetError(err *Error) {
    x.Error = err
}

func (x *ListFactionsRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListFactionsRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListFactionsResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListFactionsResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListFactionsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *Relationship) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Relationship) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *WorldStatus) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *WorldStatus) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *World) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *World) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetWorldsRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetWorldsRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetWorldsResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetWorldsResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetWorldsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *SetWorldRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetWorldRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetWorldResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetWorldResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetWorldResponse) SetError(err *Error) {
    x.Error = err
}

func (x *DeleteWorldRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteWorldRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteWorldResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteWorldResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteWorldResponse) SetError(err *Error) {
    x.Error = err
}

func (x *ListWorldsRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListWorldsRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListWorldsResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListWorldsResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListWorldsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *Error) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Error) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Metaref) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Metaref) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Memory) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Memory) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Change) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Change) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *OnChangeRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *OnChangeRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *OnChangeResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *OnChangeResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *OnChangeResponse) SetError(err *Error) {
    x.Error = err
}

func (x *ActorStatus) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ActorStatus) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Actor) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Actor) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetActorsRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetActorsRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetActorsResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetActorsResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetActorsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *SetActorsRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetActorsRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetActorsResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetActorsResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetActorsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *DeleteActorRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteActorRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteActorResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteActorResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteActorResponse) SetError(err *Error) {
    x.Error = err
}

func (x *ListActorsRequest) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListActorsRequest) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListActorsResponse) Marshal() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListActorsResponse) Unmarshal(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListActorsResponse) SetError(err *Error) {
    x.Error = err
}
