// FILE IS AUTOGENERATED. DO NOT EDIT!
package structs

import (
    "google.golang.org/protobuf/encoding/protojson"

    "buf.build/go/protoyaml"
)

func (x *Affiliation) Kind() string {
    return "Affiliation"
}

func (x *Affiliation) New() *Affiliation {
    return &Affiliation{}
}

func (x *Affiliation) NewSlice() []*Affiliation {
    return []*Affiliation{}
}

func (x *Affiliation) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *Affiliation) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *Affiliation) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Affiliation) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Faction) Kind() string {
    return "Faction"
}

func (x *Faction) New() *Faction {
    return &Faction{}
}

func (x *Faction) NewSlice() []*Faction {
    return []*Faction{}
}

func (x *Faction) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *Faction) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *Faction) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Faction) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *FactionStatus) Kind() string {
    return "FactionStatus"
}

func (x *FactionStatus) New() *FactionStatus {
    return &FactionStatus{}
}

func (x *FactionStatus) NewSlice() []*FactionStatus {
    return []*FactionStatus{}
}

func (x *FactionStatus) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *FactionStatus) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *FactionStatus) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *FactionStatus) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetFactionsRequest) Kind() string {
    return "GetFactionsRequest"
}

func (x *GetFactionsRequest) New() *GetFactionsRequest {
    return &GetFactionsRequest{}
}

func (x *GetFactionsRequest) NewSlice() []*GetFactionsRequest {
    return []*GetFactionsRequest{}
}

func (x *GetFactionsRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *GetFactionsRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *GetFactionsRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetFactionsRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetFactionsResponse) Kind() string {
    return "GetFactionsResponse"
}

func (x *GetFactionsResponse) New() *GetFactionsResponse {
    return &GetFactionsResponse{}
}

func (x *GetFactionsResponse) NewSlice() []*GetFactionsResponse {
    return []*GetFactionsResponse{}
}

func (x *GetFactionsResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *GetFactionsResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *GetFactionsResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetFactionsResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetFactionsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *SetFactionsRequest) Kind() string {
    return "SetFactionsRequest"
}

func (x *SetFactionsRequest) New() *SetFactionsRequest {
    return &SetFactionsRequest{}
}

func (x *SetFactionsRequest) NewSlice() []*SetFactionsRequest {
    return []*SetFactionsRequest{}
}

func (x *SetFactionsRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *SetFactionsRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *SetFactionsRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetFactionsRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetFactionsResponse) Kind() string {
    return "SetFactionsResponse"
}

func (x *SetFactionsResponse) New() *SetFactionsResponse {
    return &SetFactionsResponse{}
}

func (x *SetFactionsResponse) NewSlice() []*SetFactionsResponse {
    return []*SetFactionsResponse{}
}

func (x *SetFactionsResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *SetFactionsResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *SetFactionsResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetFactionsResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetFactionsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *DeleteFactionRequest) Kind() string {
    return "DeleteFactionRequest"
}

func (x *DeleteFactionRequest) New() *DeleteFactionRequest {
    return &DeleteFactionRequest{}
}

func (x *DeleteFactionRequest) NewSlice() []*DeleteFactionRequest {
    return []*DeleteFactionRequest{}
}

func (x *DeleteFactionRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *DeleteFactionRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *DeleteFactionRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteFactionRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteFactionResponse) Kind() string {
    return "DeleteFactionResponse"
}

func (x *DeleteFactionResponse) New() *DeleteFactionResponse {
    return &DeleteFactionResponse{}
}

func (x *DeleteFactionResponse) NewSlice() []*DeleteFactionResponse {
    return []*DeleteFactionResponse{}
}

func (x *DeleteFactionResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *DeleteFactionResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *DeleteFactionResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteFactionResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteFactionResponse) SetError(err *Error) {
    x.Error = err
}

func (x *ListFactionsRequest) Kind() string {
    return "ListFactionsRequest"
}

func (x *ListFactionsRequest) New() *ListFactionsRequest {
    return &ListFactionsRequest{}
}

func (x *ListFactionsRequest) NewSlice() []*ListFactionsRequest {
    return []*ListFactionsRequest{}
}

func (x *ListFactionsRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *ListFactionsRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *ListFactionsRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListFactionsRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListFactionsResponse) Kind() string {
    return "ListFactionsResponse"
}

func (x *ListFactionsResponse) New() *ListFactionsResponse {
    return &ListFactionsResponse{}
}

func (x *ListFactionsResponse) NewSlice() []*ListFactionsResponse {
    return []*ListFactionsResponse{}
}

func (x *ListFactionsResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *ListFactionsResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *ListFactionsResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListFactionsResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListFactionsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *Relationship) Kind() string {
    return "Relationship"
}

func (x *Relationship) New() *Relationship {
    return &Relationship{}
}

func (x *Relationship) NewSlice() []*Relationship {
    return []*Relationship{}
}

func (x *Relationship) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *Relationship) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *Relationship) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Relationship) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *WorldStatus) Kind() string {
    return "WorldStatus"
}

func (x *WorldStatus) New() *WorldStatus {
    return &WorldStatus{}
}

func (x *WorldStatus) NewSlice() []*WorldStatus {
    return []*WorldStatus{}
}

func (x *WorldStatus) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *WorldStatus) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *WorldStatus) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *WorldStatus) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *World) Kind() string {
    return "World"
}

func (x *World) New() *World {
    return &World{}
}

func (x *World) NewSlice() []*World {
    return []*World{}
}

func (x *World) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *World) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *World) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *World) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetWorldsRequest) Kind() string {
    return "GetWorldsRequest"
}

func (x *GetWorldsRequest) New() *GetWorldsRequest {
    return &GetWorldsRequest{}
}

func (x *GetWorldsRequest) NewSlice() []*GetWorldsRequest {
    return []*GetWorldsRequest{}
}

func (x *GetWorldsRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *GetWorldsRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *GetWorldsRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetWorldsRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetWorldsResponse) Kind() string {
    return "GetWorldsResponse"
}

func (x *GetWorldsResponse) New() *GetWorldsResponse {
    return &GetWorldsResponse{}
}

func (x *GetWorldsResponse) NewSlice() []*GetWorldsResponse {
    return []*GetWorldsResponse{}
}

func (x *GetWorldsResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *GetWorldsResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *GetWorldsResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetWorldsResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetWorldsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *SetWorldRequest) Kind() string {
    return "SetWorldRequest"
}

func (x *SetWorldRequest) New() *SetWorldRequest {
    return &SetWorldRequest{}
}

func (x *SetWorldRequest) NewSlice() []*SetWorldRequest {
    return []*SetWorldRequest{}
}

func (x *SetWorldRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *SetWorldRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *SetWorldRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetWorldRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetWorldResponse) Kind() string {
    return "SetWorldResponse"
}

func (x *SetWorldResponse) New() *SetWorldResponse {
    return &SetWorldResponse{}
}

func (x *SetWorldResponse) NewSlice() []*SetWorldResponse {
    return []*SetWorldResponse{}
}

func (x *SetWorldResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *SetWorldResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *SetWorldResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetWorldResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetWorldResponse) SetError(err *Error) {
    x.Error = err
}

func (x *DeleteWorldRequest) Kind() string {
    return "DeleteWorldRequest"
}

func (x *DeleteWorldRequest) New() *DeleteWorldRequest {
    return &DeleteWorldRequest{}
}

func (x *DeleteWorldRequest) NewSlice() []*DeleteWorldRequest {
    return []*DeleteWorldRequest{}
}

func (x *DeleteWorldRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *DeleteWorldRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *DeleteWorldRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteWorldRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteWorldResponse) Kind() string {
    return "DeleteWorldResponse"
}

func (x *DeleteWorldResponse) New() *DeleteWorldResponse {
    return &DeleteWorldResponse{}
}

func (x *DeleteWorldResponse) NewSlice() []*DeleteWorldResponse {
    return []*DeleteWorldResponse{}
}

func (x *DeleteWorldResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *DeleteWorldResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *DeleteWorldResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteWorldResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteWorldResponse) SetError(err *Error) {
    x.Error = err
}

func (x *ListWorldsRequest) Kind() string {
    return "ListWorldsRequest"
}

func (x *ListWorldsRequest) New() *ListWorldsRequest {
    return &ListWorldsRequest{}
}

func (x *ListWorldsRequest) NewSlice() []*ListWorldsRequest {
    return []*ListWorldsRequest{}
}

func (x *ListWorldsRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *ListWorldsRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *ListWorldsRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListWorldsRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListWorldsResponse) Kind() string {
    return "ListWorldsResponse"
}

func (x *ListWorldsResponse) New() *ListWorldsResponse {
    return &ListWorldsResponse{}
}

func (x *ListWorldsResponse) NewSlice() []*ListWorldsResponse {
    return []*ListWorldsResponse{}
}

func (x *ListWorldsResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *ListWorldsResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *ListWorldsResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListWorldsResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListWorldsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *Error) Kind() string {
    return "Error"
}

func (x *Error) New() *Error {
    return &Error{}
}

func (x *Error) NewSlice() []*Error {
    return []*Error{}
}

func (x *Error) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *Error) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *Error) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Error) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Metaref) Kind() string {
    return "Metaref"
}

func (x *Metaref) New() *Metaref {
    return &Metaref{}
}

func (x *Metaref) NewSlice() []*Metaref {
    return []*Metaref{}
}

func (x *Metaref) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *Metaref) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *Metaref) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Metaref) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Memory) Kind() string {
    return "Memory"
}

func (x *Memory) New() *Memory {
    return &Memory{}
}

func (x *Memory) NewSlice() []*Memory {
    return []*Memory{}
}

func (x *Memory) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *Memory) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *Memory) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Memory) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Change) Kind() string {
    return "Change"
}

func (x *Change) New() *Change {
    return &Change{}
}

func (x *Change) NewSlice() []*Change {
    return []*Change{}
}

func (x *Change) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *Change) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *Change) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Change) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *OnChangeRequest) Kind() string {
    return "OnChangeRequest"
}

func (x *OnChangeRequest) New() *OnChangeRequest {
    return &OnChangeRequest{}
}

func (x *OnChangeRequest) NewSlice() []*OnChangeRequest {
    return []*OnChangeRequest{}
}

func (x *OnChangeRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *OnChangeRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *OnChangeRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *OnChangeRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *OnChangeResponse) Kind() string {
    return "OnChangeResponse"
}

func (x *OnChangeResponse) New() *OnChangeResponse {
    return &OnChangeResponse{}
}

func (x *OnChangeResponse) NewSlice() []*OnChangeResponse {
    return []*OnChangeResponse{}
}

func (x *OnChangeResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *OnChangeResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *OnChangeResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *OnChangeResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *OnChangeResponse) SetError(err *Error) {
    x.Error = err
}

func (x *ActorStatus) Kind() string {
    return "ActorStatus"
}

func (x *ActorStatus) New() *ActorStatus {
    return &ActorStatus{}
}

func (x *ActorStatus) NewSlice() []*ActorStatus {
    return []*ActorStatus{}
}

func (x *ActorStatus) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *ActorStatus) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *ActorStatus) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ActorStatus) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *Actor) Kind() string {
    return "Actor"
}

func (x *Actor) New() *Actor {
    return &Actor{}
}

func (x *Actor) NewSlice() []*Actor {
    return []*Actor{}
}

func (x *Actor) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *Actor) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *Actor) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *Actor) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetActorsRequest) Kind() string {
    return "GetActorsRequest"
}

func (x *GetActorsRequest) New() *GetActorsRequest {
    return &GetActorsRequest{}
}

func (x *GetActorsRequest) NewSlice() []*GetActorsRequest {
    return []*GetActorsRequest{}
}

func (x *GetActorsRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *GetActorsRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *GetActorsRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetActorsRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetActorsResponse) Kind() string {
    return "GetActorsResponse"
}

func (x *GetActorsResponse) New() *GetActorsResponse {
    return &GetActorsResponse{}
}

func (x *GetActorsResponse) NewSlice() []*GetActorsResponse {
    return []*GetActorsResponse{}
}

func (x *GetActorsResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *GetActorsResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *GetActorsResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *GetActorsResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *GetActorsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *SetActorsRequest) Kind() string {
    return "SetActorsRequest"
}

func (x *SetActorsRequest) New() *SetActorsRequest {
    return &SetActorsRequest{}
}

func (x *SetActorsRequest) NewSlice() []*SetActorsRequest {
    return []*SetActorsRequest{}
}

func (x *SetActorsRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *SetActorsRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *SetActorsRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetActorsRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetActorsResponse) Kind() string {
    return "SetActorsResponse"
}

func (x *SetActorsResponse) New() *SetActorsResponse {
    return &SetActorsResponse{}
}

func (x *SetActorsResponse) NewSlice() []*SetActorsResponse {
    return []*SetActorsResponse{}
}

func (x *SetActorsResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *SetActorsResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *SetActorsResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *SetActorsResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *SetActorsResponse) SetError(err *Error) {
    x.Error = err
}

func (x *DeleteActorRequest) Kind() string {
    return "DeleteActorRequest"
}

func (x *DeleteActorRequest) New() *DeleteActorRequest {
    return &DeleteActorRequest{}
}

func (x *DeleteActorRequest) NewSlice() []*DeleteActorRequest {
    return []*DeleteActorRequest{}
}

func (x *DeleteActorRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *DeleteActorRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *DeleteActorRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteActorRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteActorResponse) Kind() string {
    return "DeleteActorResponse"
}

func (x *DeleteActorResponse) New() *DeleteActorResponse {
    return &DeleteActorResponse{}
}

func (x *DeleteActorResponse) NewSlice() []*DeleteActorResponse {
    return []*DeleteActorResponse{}
}

func (x *DeleteActorResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *DeleteActorResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *DeleteActorResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *DeleteActorResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *DeleteActorResponse) SetError(err *Error) {
    x.Error = err
}

func (x *ListActorsRequest) Kind() string {
    return "ListActorsRequest"
}

func (x *ListActorsRequest) New() *ListActorsRequest {
    return &ListActorsRequest{}
}

func (x *ListActorsRequest) NewSlice() []*ListActorsRequest {
    return []*ListActorsRequest{}
}

func (x *ListActorsRequest) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *ListActorsRequest) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *ListActorsRequest) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListActorsRequest) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListActorsResponse) Kind() string {
    return "ListActorsResponse"
}

func (x *ListActorsResponse) New() *ListActorsResponse {
    return &ListActorsResponse{}
}

func (x *ListActorsResponse) NewSlice() []*ListActorsResponse {
    return []*ListActorsResponse{}
}

func (x *ListActorsResponse) MarshalYAML() ([]byte, error) {
    return protoyaml.Marshal(x)
}

func (x *ListActorsResponse) UnmarshalYAML(data []byte) error {
    return protoyaml.Unmarshal(data, x)
}

func (x *ListActorsResponse) MarshalJSON() ([]byte, error) {
    return protojson.Marshal(x)
}

func (x *ListActorsResponse) UnmarshalJSON(data []byte) error {
    return protojson.Unmarshal(data, x)
}

func (x *ListActorsResponse) SetError(err *Error) {
    x.Error = err
}
