// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: ethos.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ethos is a set of guiding principles that someone (or a faction) abides by,
// and how strongly the do so (or do not).
type Ethos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Altruism is unselfish concern for the welfare of others.
	//
	// High altruism implies selflessness, self sacrifice etc.
	// Low altruism implies selfishness, the complete lack of concern for others.
	Altruism int64 `protobuf:"zigzag64,1,opt,name=Altruism,proto3" json:"Altruism,omitempty"`
	// Ambition is the desire to get ahead in society, to obtain riches, honors, power etc.
	//
	// High ambition implies the willingness to go the extra mile, to work hard, to strive upwards.
	// Low ambition implies the lack of desire to improve ones station.
	Ambition int64 `protobuf:"zigzag64,2,opt,name=Ambition,proto3" json:"Ambition,omitempty"`
	// Tradition is a measure of ones desire to stay within the laws and traditions of one's society, culture, laws etc.
	//
	// High tradition implies a (generally) law abiding outlook, great value placed on shared culture & values.
	// Low tradition implies a more chaotic, devil-may-care outlook, considering tradition(s) too confining and
	// (possibly even) laws too restrictive.
	Tradition int64 `protobuf:"zigzag64,3,opt,name=Tradition,proto3" json:"Tradition,omitempty"`
	// Pacifism is dedication to peace, eschewing violence & conflict.
	//
	// High pacifism implies one takes great pains avoid harming others, possibly even preferring death.
	// Low pacifism implies a strong propensity to violence.
	Pacifism int64 `protobuf:"zigzag64,4,opt,name=Pacifism,proto3" json:"Pacifism,omitempty"`
	// Piety is faith in the divine, religious devotion.
	//
	// High piety implies strict adherence to ones faith & it's tenants.
	// Low piety implies no adherence to a faith.
	Piety int64 `protobuf:"zigzag64,5,opt,name=Piety,proto3" json:"Piety,omitempty"`
	// Caution is the propensity is calculate carefully & weigh up risks before acting.
	//
	// High caution implies very deliberate, well thought out choices, multiple safeguards and counter strategies.
	// Low caution implies recklessness, the propensity to act without thinking; "there is no plan"
	Caution int64 `protobuf:"zigzag64,6,opt,name=Caution,proto3" json:"Caution,omitempty"`
}

func (x *Ethos) Reset() {
	*x = Ethos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ethos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ethos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ethos) ProtoMessage() {}

func (x *Ethos) ProtoReflect() protoreflect.Message {
	mi := &file_ethos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ethos.ProtoReflect.Descriptor instead.
func (*Ethos) Descriptor() ([]byte, []int) {
	return file_ethos_proto_rawDescGZIP(), []int{0}
}

func (x *Ethos) GetAltruism() int64 {
	if x != nil {
		return x.Altruism
	}
	return 0
}

func (x *Ethos) GetAmbition() int64 {
	if x != nil {
		return x.Ambition
	}
	return 0
}

func (x *Ethos) GetTradition() int64 {
	if x != nil {
		return x.Tradition
	}
	return 0
}

func (x *Ethos) GetPacifism() int64 {
	if x != nil {
		return x.Pacifism
	}
	return 0
}

func (x *Ethos) GetPiety() int64 {
	if x != nil {
		return x.Piety
	}
	return 0
}

func (x *Ethos) GetCaution() int64 {
	if x != nil {
		return x.Caution
	}
	return 0
}

var File_ethos_proto protoreflect.FileDescriptor

var file_ethos_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x74, 0x68, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x01,
	0x0a, 0x05, 0x45, 0x74, 0x68, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x6c, 0x74, 0x72, 0x75,
	0x69, 0x73, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x08, 0x41, 0x6c, 0x74, 0x72, 0x75,
	0x69, 0x73, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x6d, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x12, 0x52, 0x08, 0x41, 0x6d, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x12, 0x52, 0x09, 0x54, 0x72, 0x61, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x63, 0x69, 0x66, 0x69, 0x73, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x12, 0x52,
	0x08, 0x50, 0x61, 0x63, 0x69, 0x66, 0x69, 0x73, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x69, 0x65,
	0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x12, 0x52, 0x05, 0x50, 0x69, 0x65, 0x74, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x61, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x12,
	0x52, 0x07, 0x43, 0x61, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x6b, 0x67,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ethos_proto_rawDescOnce sync.Once
	file_ethos_proto_rawDescData = file_ethos_proto_rawDesc
)

func file_ethos_proto_rawDescGZIP() []byte {
	file_ethos_proto_rawDescOnce.Do(func() {
		file_ethos_proto_rawDescData = protoimpl.X.CompressGZIP(file_ethos_proto_rawDescData)
	})
	return file_ethos_proto_rawDescData
}

var file_ethos_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ethos_proto_goTypes = []interface{}{
	(*Ethos)(nil), // 0: Ethos
}
var file_ethos_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ethos_proto_init() }
func file_ethos_proto_init() {
	if File_ethos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ethos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ethos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ethos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ethos_proto_goTypes,
		DependencyIndexes: file_ethos_proto_depIdxs,
		MessageInfos:      file_ethos_proto_msgTypes,
	}.Build()
	File_ethos_proto = out.File
	file_ethos_proto_rawDesc = nil
	file_ethos_proto_goTypes = nil
	file_ethos_proto_depIdxs = nil
}
