// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: faction_structure.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactionStructure int32

const (
	FactionStructure_Pyramid FactionStructure = 0
	FactionStructure_Loose   FactionStructure = 1
	FactionStructure_Cell    FactionStructure = 2
)

// Enum value maps for FactionStructure.
var (
	FactionStructure_name = map[int32]string{
		0: "Pyramid",
		1: "Loose",
		2: "Cell",
	}
	FactionStructure_value = map[string]int32{
		"Pyramid": 0,
		"Loose":   1,
		"Cell":    2,
	}
)

func (x FactionStructure) Enum() *FactionStructure {
	p := new(FactionStructure)
	*p = x
	return p
}

func (x FactionStructure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FactionStructure) Descriptor() protoreflect.EnumDescriptor {
	return file_faction_structure_proto_enumTypes[0].Descriptor()
}

func (FactionStructure) Type() protoreflect.EnumType {
	return &file_faction_structure_proto_enumTypes[0]
}

func (x FactionStructure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FactionStructure.Descriptor instead.
func (FactionStructure) EnumDescriptor() ([]byte, []int) {
	return file_faction_structure_proto_rawDescGZIP(), []int{0}
}

var File_faction_structure_proto protoreflect.FileDescriptor

var file_faction_structure_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x34, 0x0a, 0x10, 0x46, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x79, 0x72, 0x61, 0x6d, 0x69, 0x64, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x6f,
	0x6f, 0x73, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x65, 0x6c, 0x6c, 0x10, 0x02, 0x42,
	0x0d, 0x5a, 0x0b, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faction_structure_proto_rawDescOnce sync.Once
	file_faction_structure_proto_rawDescData = file_faction_structure_proto_rawDesc
)

func file_faction_structure_proto_rawDescGZIP() []byte {
	file_faction_structure_proto_rawDescOnce.Do(func() {
		file_faction_structure_proto_rawDescData = protoimpl.X.CompressGZIP(file_faction_structure_proto_rawDescData)
	})
	return file_faction_structure_proto_rawDescData
}

var file_faction_structure_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_faction_structure_proto_goTypes = []interface{}{
	(FactionStructure)(0), // 0: FactionStructure
}
var file_faction_structure_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faction_structure_proto_init() }
func file_faction_structure_proto_init() {
	if File_faction_structure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faction_structure_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_faction_structure_proto_goTypes,
		DependencyIndexes: file_faction_structure_proto_depIdxs,
		EnumInfos:         file_faction_structure_proto_enumTypes,
	}.Build()
	File_faction_structure_proto = out.File
	file_faction_structure_proto_rawDesc = nil
	file_faction_structure_proto_goTypes = nil
	file_faction_structure_proto_depIdxs = nil
}
