// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: faction_relation.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactionRelation int32

const (
	FactionRelation_Tributary FactionRelation = 0 // pays tax to super faction, but does it's own thing
	FactionRelation_Puppet    FactionRelation = 1 // strictly subordinate, very little self rule
	FactionRelation_Vassal    FactionRelation = 2 // strictly subordinate, but with regin over it's own affairs
	FactionRelation_Member    FactionRelation = 3 // equal member of a super faction (ie. members of the EU)
)

// Enum value maps for FactionRelation.
var (
	FactionRelation_name = map[int32]string{
		0: "Tributary",
		1: "Puppet",
		2: "Vassal",
		3: "Member",
	}
	FactionRelation_value = map[string]int32{
		"Tributary": 0,
		"Puppet":    1,
		"Vassal":    2,
		"Member":    3,
	}
)

func (x FactionRelation) Enum() *FactionRelation {
	p := new(FactionRelation)
	*p = x
	return p
}

func (x FactionRelation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FactionRelation) Descriptor() protoreflect.EnumDescriptor {
	return file_faction_relation_proto_enumTypes[0].Descriptor()
}

func (FactionRelation) Type() protoreflect.EnumType {
	return &file_faction_relation_proto_enumTypes[0]
}

func (x FactionRelation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FactionRelation.Descriptor instead.
func (FactionRelation) EnumDescriptor() ([]byte, []int) {
	return file_faction_relation_proto_rawDescGZIP(), []int{0}
}

var File_faction_relation_proto protoreflect.FileDescriptor

var file_faction_relation_proto_rawDesc = []byte{
	0x0a, 0x16, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x44, 0x0a, 0x0f, 0x46, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x61, 0x72, 0x79, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x75,
	0x70, 0x70, 0x65, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x61, 0x73, 0x73, 0x61, 0x6c,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x03, 0x42, 0x0d,
	0x5a, 0x0b, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faction_relation_proto_rawDescOnce sync.Once
	file_faction_relation_proto_rawDescData = file_faction_relation_proto_rawDesc
)

func file_faction_relation_proto_rawDescGZIP() []byte {
	file_faction_relation_proto_rawDescOnce.Do(func() {
		file_faction_relation_proto_rawDescData = protoimpl.X.CompressGZIP(file_faction_relation_proto_rawDescData)
	})
	return file_faction_relation_proto_rawDescData
}

var file_faction_relation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_faction_relation_proto_goTypes = []interface{}{
	(FactionRelation)(0), // 0: FactionRelation
}
var file_faction_relation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faction_relation_proto_init() }
func file_faction_relation_proto_init() {
	if File_faction_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faction_relation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_faction_relation_proto_goTypes,
		DependencyIndexes: file_faction_relation_proto_depIdxs,
		EnumInfos:         file_faction_relation_proto_enumTypes,
	}.Build()
	File_faction_relation_proto = out.File
	file_faction_relation_proto_rawDesc = nil
	file_faction_relation_proto_goTypes = nil
	file_faction_relation_proto_depIdxs = nil
}
