// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: faction_leadership.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactionLeadership int32

const (
	FactionLeadership_Single  FactionLeadership = 0
	FactionLeadership_Dual    FactionLeadership = 1
	FactionLeadership_Triad   FactionLeadership = 2
	FactionLeadership_Council FactionLeadership = 3
	FactionLeadership_All     FactionLeadership = 4
)

// Enum value maps for FactionLeadership.
var (
	FactionLeadership_name = map[int32]string{
		0: "Single",
		1: "Dual",
		2: "Triad",
		3: "Council",
		4: "All",
	}
	FactionLeadership_value = map[string]int32{
		"Single":  0,
		"Dual":    1,
		"Triad":   2,
		"Council": 3,
		"All":     4,
	}
)

func (x FactionLeadership) Enum() *FactionLeadership {
	p := new(FactionLeadership)
	*p = x
	return p
}

func (x FactionLeadership) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FactionLeadership) Descriptor() protoreflect.EnumDescriptor {
	return file_faction_leadership_proto_enumTypes[0].Descriptor()
}

func (FactionLeadership) Type() protoreflect.EnumType {
	return &file_faction_leadership_proto_enumTypes[0]
}

func (x FactionLeadership) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FactionLeadership.Descriptor instead.
func (FactionLeadership) EnumDescriptor() ([]byte, []int) {
	return file_faction_leadership_proto_rawDescGZIP(), []int{0}
}

var File_faction_leadership_proto protoreflect.FileDescriptor

var file_faction_leadership_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x4a, 0x0a, 0x11, 0x46, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44,
	0x75, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x72, 0x69, 0x61, 0x64, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x63, 0x69, 0x6c, 0x10, 0x03, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x6c, 0x6c, 0x10, 0x04, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faction_leadership_proto_rawDescOnce sync.Once
	file_faction_leadership_proto_rawDescData = file_faction_leadership_proto_rawDesc
)

func file_faction_leadership_proto_rawDescGZIP() []byte {
	file_faction_leadership_proto_rawDescOnce.Do(func() {
		file_faction_leadership_proto_rawDescData = protoimpl.X.CompressGZIP(file_faction_leadership_proto_rawDescData)
	})
	return file_faction_leadership_proto_rawDescData
}

var file_faction_leadership_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_faction_leadership_proto_goTypes = []interface{}{
	(FactionLeadership)(0), // 0: FactionLeadership
}
var file_faction_leadership_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faction_leadership_proto_init() }
func file_faction_leadership_proto_init() {
	if File_faction_leadership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faction_leadership_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_faction_leadership_proto_goTypes,
		DependencyIndexes: file_faction_leadership_proto_depIdxs,
		EnumInfos:         file_faction_leadership_proto_enumTypes,
	}.Build()
	File_faction_leadership_proto = out.File
	file_faction_leadership_proto_rawDesc = nil
	file_faction_leadership_proto_goTypes = nil
	file_faction_leadership_proto_depIdxs = nil
}
