// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: faction_rank.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactionRank int32

const (
	FactionRank_Associate   FactionRank = 0
	FactionRank_Apprentice  FactionRank = 1
	FactionRank_Novice      FactionRank = 2
	FactionRank_Journeyman  FactionRank = 3
	FactionRank_Adept       FactionRank = 4
	FactionRank_Expert      FactionRank = 5
	FactionRank_Master      FactionRank = 6
	FactionRank_GrandMaster FactionRank = 7
	FactionRank_Elder       FactionRank = 8
	FactionRank_Ruler       FactionRank = 9
)

// Enum value maps for FactionRank.
var (
	FactionRank_name = map[int32]string{
		0: "Associate",
		1: "Apprentice",
		2: "Novice",
		3: "Journeyman",
		4: "Adept",
		5: "Expert",
		6: "Master",
		7: "GrandMaster",
		8: "Elder",
		9: "Ruler",
	}
	FactionRank_value = map[string]int32{
		"Associate":   0,
		"Apprentice":  1,
		"Novice":      2,
		"Journeyman":  3,
		"Adept":       4,
		"Expert":      5,
		"Master":      6,
		"GrandMaster": 7,
		"Elder":       8,
		"Ruler":       9,
	}
)

func (x FactionRank) Enum() *FactionRank {
	p := new(FactionRank)
	*p = x
	return p
}

func (x FactionRank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FactionRank) Descriptor() protoreflect.EnumDescriptor {
	return file_faction_rank_proto_enumTypes[0].Descriptor()
}

func (FactionRank) Type() protoreflect.EnumType {
	return &file_faction_rank_proto_enumTypes[0]
}

func (x FactionRank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FactionRank.Descriptor instead.
func (FactionRank) EnumDescriptor() ([]byte, []int) {
	return file_faction_rank_proto_rawDescGZIP(), []int{0}
}

var File_faction_rank_proto protoreflect.FileDescriptor

var file_faction_rank_proto_rawDesc = []byte{
	0x0a, 0x12, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x92, 0x01, 0x0a, 0x0b, 0x46, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x61, 0x6e, 0x6b, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74,
	0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x72, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x76, 0x69, 0x63, 0x65, 0x10, 0x02, 0x12,
	0x0e, 0x0a, 0x0a, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x79, 0x6d, 0x61, 0x6e, 0x10, 0x03, 0x12,
	0x09, 0x0a, 0x05, 0x41, 0x64, 0x65, 0x70, 0x74, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x78,
	0x70, 0x65, 0x72, 0x74, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x72, 0x61, 0x6e, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x6c, 0x64, 0x65, 0x72, 0x10, 0x08, 0x12, 0x09,
	0x0a, 0x05, 0x52, 0x75, 0x6c, 0x65, 0x72, 0x10, 0x09, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x6b, 0x67,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faction_rank_proto_rawDescOnce sync.Once
	file_faction_rank_proto_rawDescData = file_faction_rank_proto_rawDesc
)

func file_faction_rank_proto_rawDescGZIP() []byte {
	file_faction_rank_proto_rawDescOnce.Do(func() {
		file_faction_rank_proto_rawDescData = protoimpl.X.CompressGZIP(file_faction_rank_proto_rawDescData)
	})
	return file_faction_rank_proto_rawDescData
}

var file_faction_rank_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_faction_rank_proto_goTypes = []interface{}{
	(FactionRank)(0), // 0: FactionRank
}
var file_faction_rank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faction_rank_proto_init() }
func file_faction_rank_proto_init() {
	if File_faction_rank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faction_rank_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_faction_rank_proto_goTypes,
		DependencyIndexes: file_faction_rank_proto_depIdxs,
		EnumInfos:         file_faction_rank_proto_enumTypes,
	}.Build()
	File_faction_rank_proto = out.File
	file_faction_rank_proto_rawDesc = nil
	file_faction_rank_proto_goTypes = nil
	file_faction_rank_proto_depIdxs = nil
}
