// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: goal.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Goal int32

const (
	Goal_Wealth    Goal = 0 // all the glitters is gold
	Goal_Growth    Goal = 1 // expand the population
	Goal_Territory Goal = 2 // expand the empire
	Goal_Power     Goal = 3 // destroy rivals
	Goal_Piety     Goal = 4 // spread the faith
	Goal_Research  Goal = 5 // research
	Goal_Military  Goal = 6 // build an army
	Goal_Diplomacy Goal = 7 // make friends
	Goal_Espionage Goal = 8 // spy on rivals
	Goal_Stability Goal = 9 // keep the peace
)

// Enum value maps for Goal.
var (
	Goal_name = map[int32]string{
		0: "Wealth",
		1: "Growth",
		2: "Territory",
		3: "Power",
		4: "Piety",
		5: "Research",
		6: "Military",
		7: "Diplomacy",
		8: "Espionage",
		9: "Stability",
	}
	Goal_value = map[string]int32{
		"Wealth":    0,
		"Growth":    1,
		"Territory": 2,
		"Power":     3,
		"Piety":     4,
		"Research":  5,
		"Military":  6,
		"Diplomacy": 7,
		"Espionage": 8,
		"Stability": 9,
	}
)

func (x Goal) Enum() *Goal {
	p := new(Goal)
	*p = x
	return p
}

func (x Goal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Goal) Descriptor() protoreflect.EnumDescriptor {
	return file_goal_proto_enumTypes[0].Descriptor()
}

func (Goal) Type() protoreflect.EnumType {
	return &file_goal_proto_enumTypes[0]
}

func (x Goal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Goal.Descriptor instead.
func (Goal) EnumDescriptor() ([]byte, []int) {
	return file_goal_proto_rawDescGZIP(), []int{0}
}

var File_goal_proto protoreflect.FileDescriptor

var file_goal_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x6f, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x8c, 0x01, 0x0a,
	0x04, 0x47, 0x6f, 0x61, 0x6c, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x54, 0x65, 0x72, 0x72, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05,
	0x50, 0x6f, 0x77, 0x65, 0x72, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x69, 0x65, 0x74, 0x79,
	0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x10, 0x05,
	0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x69, 0x6c, 0x69, 0x74, 0x61, 0x72, 0x79, 0x10, 0x06, 0x12, 0x0d,
	0x0a, 0x09, 0x44, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61, 0x63, 0x79, 0x10, 0x07, 0x12, 0x0d, 0x0a,
	0x09, 0x45, 0x73, 0x70, 0x69, 0x6f, 0x6e, 0x61, 0x67, 0x65, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x10, 0x09, 0x42, 0x0d, 0x5a, 0x0b, 0x70,
	0x6b, 0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_goal_proto_rawDescOnce sync.Once
	file_goal_proto_rawDescData = file_goal_proto_rawDesc
)

func file_goal_proto_rawDescGZIP() []byte {
	file_goal_proto_rawDescOnce.Do(func() {
		file_goal_proto_rawDescData = protoimpl.X.CompressGZIP(file_goal_proto_rawDescData)
	})
	return file_goal_proto_rawDescData
}

var file_goal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goal_proto_goTypes = []interface{}{
	(Goal)(0), // 0: Goal
}
var file_goal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goal_proto_init() }
func file_goal_proto_init() {
	if File_goal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goal_proto_goTypes,
		DependencyIndexes: file_goal_proto_depIdxs,
		EnumInfos:         file_goal_proto_enumTypes,
	}.Build()
	File_goal_proto = out.File
	file_goal_proto_rawDesc = nil
	file_goal_proto_goTypes = nil
	file_goal_proto_depIdxs = nil
}
