// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: meta.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta int32

const (
	Meta_KeyPerson     Meta = 0  // targets specific person Val: PERSON_ID
	Meta_KeyPlot       Meta = 1  // targets specific plot Val: PLOT_ID
	Meta_KeyResearch   Meta = 2  // targets specific research Val: RESEARCH_TOPIC
	Meta_KeyFaction    Meta = 3  // targets specific faction Val: FACTION_ID
	Meta_KeyReligion   Meta = 4  // targets specific religion Val: RELIGION_ID
	Meta_KeyGovernment Meta = 5  // targets specific government Val: GOVERNMENT_ID
	Meta_KeyFamily     Meta = 6  // targets specific family Val: FAMILY_ID
	Meta_KeyCommodity  Meta = 7  // targets specific commodity Val: COMMODITY_NAME
	Meta_KeyAction     Meta = 8  // targets specific action Val: ACTION_TYPE
	Meta_KeyJob        Meta = 9  // targets specific job Val: JOB_ID
	Meta_KeyArea       Meta = 10 // targets specific area Val: AREA_ID
	Meta_KeyEvent      Meta = 11 // targets specific event Val: EVENT_ID
	Meta_KeyGoal       Meta = 12 // targets specific goal Val: GOAL_NAME
)

// Enum value maps for Meta.
var (
	Meta_name = map[int32]string{
		0:  "KeyPerson",
		1:  "KeyPlot",
		2:  "KeyResearch",
		3:  "KeyFaction",
		4:  "KeyReligion",
		5:  "KeyGovernment",
		6:  "KeyFamily",
		7:  "KeyCommodity",
		8:  "KeyAction",
		9:  "KeyJob",
		10: "KeyArea",
		11: "KeyEvent",
		12: "KeyGoal",
	}
	Meta_value = map[string]int32{
		"KeyPerson":     0,
		"KeyPlot":       1,
		"KeyResearch":   2,
		"KeyFaction":    3,
		"KeyReligion":   4,
		"KeyGovernment": 5,
		"KeyFamily":     6,
		"KeyCommodity":  7,
		"KeyAction":     8,
		"KeyJob":        9,
		"KeyArea":       10,
		"KeyEvent":      11,
		"KeyGoal":       12,
	}
)

func (x Meta) Enum() *Meta {
	p := new(Meta)
	*p = x
	return p
}

func (x Meta) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Meta) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_proto_enumTypes[0].Descriptor()
}

func (Meta) Type() protoreflect.EnumType {
	return &file_meta_proto_enumTypes[0]
}

func (x Meta) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Meta.Descriptor instead.
func (Meta) EnumDescriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

var File_meta_proto protoreflect.FileDescriptor

var file_meta_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xcb, 0x01, 0x0a,
	0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0d, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x50, 0x6c, 0x6f, 0x74, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x65, 0x79, 0x46, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x6c, 0x69, 0x67, 0x69, 0x6f,
	0x6e, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x69, 0x74, 0x79, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x65, 0x79, 0x4a, 0x6f, 0x62,
	0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x41, 0x72, 0x65, 0x61, 0x10, 0x0a, 0x12,
	0x0c, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x0b, 0x12, 0x0b, 0x0a,
	0x07, 0x4b, 0x65, 0x79, 0x47, 0x6f, 0x61, 0x6c, 0x10, 0x0c, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x6b,
	0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData = file_meta_proto_rawDesc
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_proto_rawDescData)
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_proto_goTypes = []interface{}{
	(Meta)(0), // 0: Meta
}
var file_meta_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		EnumInfos:         file_meta_proto_enumTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_rawDesc = nil
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}
