// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: personal_relation.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PersonalRelation represents how two people know each other.
//
// In general a person is linked with the strongest relevant link.
// Ie.
// - if a person is a lover and a friend, they are considered a lover.
// - if a person is a lover and a wife, they are considered a wife.
// Nb. these are in order, where the lower number(s) trump higher ones.
type PersonalRelation int32

const (
	PersonalRelation_ExWife         PersonalRelation = 0
	PersonalRelation_ExHusband      PersonalRelation = 1
	PersonalRelation_Wife           PersonalRelation = 2
	PersonalRelation_Husband        PersonalRelation = 3
	PersonalRelation_Mother         PersonalRelation = 4
	PersonalRelation_Father         PersonalRelation = 5
	PersonalRelation_Daughter       PersonalRelation = 6
	PersonalRelation_Son            PersonalRelation = 7
	PersonalRelation_Sister         PersonalRelation = 8
	PersonalRelation_Brother        PersonalRelation = 9
	PersonalRelation_Grandmother    PersonalRelation = 10
	PersonalRelation_Grandfather    PersonalRelation = 11
	PersonalRelation_Granddaughter  PersonalRelation = 12
	PersonalRelation_Grandson       PersonalRelation = 13
	PersonalRelation_ExtendedFamily PersonalRelation = 14
	PersonalRelation_Fiancee        PersonalRelation = 15
	PersonalRelation_Lover          PersonalRelation = 16
	PersonalRelation_HatedEnemy     PersonalRelation = 17
	PersonalRelation_Enemy          PersonalRelation = 18
	PersonalRelation_CloseFriend    PersonalRelation = 19
	PersonalRelation_Friend         PersonalRelation = 20
	PersonalRelation_Mentor         PersonalRelation = 21
	PersonalRelation_Colleague      PersonalRelation = 22
)

// Enum value maps for PersonalRelation.
var (
	PersonalRelation_name = map[int32]string{
		0:  "ExWife",
		1:  "ExHusband",
		2:  "Wife",
		3:  "Husband",
		4:  "Mother",
		5:  "Father",
		6:  "Daughter",
		7:  "Son",
		8:  "Sister",
		9:  "Brother",
		10: "Grandmother",
		11: "Grandfather",
		12: "Granddaughter",
		13: "Grandson",
		14: "ExtendedFamily",
		15: "Fiancee",
		16: "Lover",
		17: "HatedEnemy",
		18: "Enemy",
		19: "CloseFriend",
		20: "Friend",
		21: "Mentor",
		22: "Colleague",
	}
	PersonalRelation_value = map[string]int32{
		"ExWife":         0,
		"ExHusband":      1,
		"Wife":           2,
		"Husband":        3,
		"Mother":         4,
		"Father":         5,
		"Daughter":       6,
		"Son":            7,
		"Sister":         8,
		"Brother":        9,
		"Grandmother":    10,
		"Grandfather":    11,
		"Granddaughter":  12,
		"Grandson":       13,
		"ExtendedFamily": 14,
		"Fiancee":        15,
		"Lover":          16,
		"HatedEnemy":     17,
		"Enemy":          18,
		"CloseFriend":    19,
		"Friend":         20,
		"Mentor":         21,
		"Colleague":      22,
	}
)

func (x PersonalRelation) Enum() *PersonalRelation {
	p := new(PersonalRelation)
	*p = x
	return p
}

func (x PersonalRelation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonalRelation) Descriptor() protoreflect.EnumDescriptor {
	return file_personal_relation_proto_enumTypes[0].Descriptor()
}

func (PersonalRelation) Type() protoreflect.EnumType {
	return &file_personal_relation_proto_enumTypes[0]
}

func (x PersonalRelation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonalRelation.Descriptor instead.
func (PersonalRelation) EnumDescriptor() ([]byte, []int) {
	return file_personal_relation_proto_rawDescGZIP(), []int{0}
}

var File_personal_relation_proto protoreflect.FileDescriptor

var file_personal_relation_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xce, 0x02, 0x0a, 0x10, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a,
	0x0a, 0x06, 0x45, 0x78, 0x57, 0x69, 0x66, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x78,
	0x48, 0x75, 0x73, 0x62, 0x61, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x69, 0x66,
	0x65, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x75, 0x73, 0x62, 0x61, 0x6e, 0x64, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x61, 0x74, 0x68, 0x65, 0x72, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x61, 0x75, 0x67,
	0x68, 0x74, 0x65, 0x72, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x6f, 0x6e, 0x10, 0x07, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x42,
	0x72, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x09, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x72, 0x61, 0x6e,
	0x64, 0x6d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x72, 0x61,
	0x6e, 0x64, 0x66, 0x61, 0x74, 0x68, 0x65, 0x72, 0x10, 0x0b, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x72,
	0x61, 0x6e, 0x64, 0x64, 0x61, 0x75, 0x67, 0x68, 0x74, 0x65, 0x72, 0x10, 0x0c, 0x12, 0x0c, 0x0a,
	0x08, 0x47, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x6f, 0x6e, 0x10, 0x0d, 0x12, 0x12, 0x0a, 0x0e, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x10, 0x0e, 0x12,
	0x0b, 0x0a, 0x07, 0x46, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x65, 0x10, 0x0f, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x6f, 0x76, 0x65, 0x72, 0x10, 0x10, 0x12, 0x0e, 0x0a, 0x0a, 0x48, 0x61, 0x74, 0x65, 0x64,
	0x45, 0x6e, 0x65, 0x6d, 0x79, 0x10, 0x11, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x6e, 0x65, 0x6d, 0x79,
	0x10, 0x12, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x10, 0x13, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x10, 0x14, 0x12,
	0x0a, 0x0a, 0x06, 0x4d, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x10, 0x15, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x10, 0x16, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x6b,
	0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_personal_relation_proto_rawDescOnce sync.Once
	file_personal_relation_proto_rawDescData = file_personal_relation_proto_rawDesc
)

func file_personal_relation_proto_rawDescGZIP() []byte {
	file_personal_relation_proto_rawDescOnce.Do(func() {
		file_personal_relation_proto_rawDescData = protoimpl.X.CompressGZIP(file_personal_relation_proto_rawDescData)
	})
	return file_personal_relation_proto_rawDescData
}

var file_personal_relation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_personal_relation_proto_goTypes = []interface{}{
	(PersonalRelation)(0), // 0: PersonalRelation
}
var file_personal_relation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_personal_relation_proto_init() }
func file_personal_relation_proto_init() {
	if File_personal_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_personal_relation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_personal_relation_proto_goTypes,
		DependencyIndexes: file_personal_relation_proto_depIdxs,
		EnumInfos:         file_personal_relation_proto_enumTypes,
	}.Build()
	File_personal_relation_proto = out.File
	file_personal_relation_proto_rawDesc = nil
	file_personal_relation_proto_goTypes = nil
	file_personal_relation_proto_depIdxs = nil
}
