// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.28.2
// source: relationship.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Relationship struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID
	ID *Metaref `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Opinion varies wildly, being swift to change based on events, but has only short term effects
	Opinion int32 `protobuf:"zigzag32,2,opt,name=Opinion,proto3" json:"Opinion,omitempty"`
	// Trust is a measure of how much the entity trusts the other entity, trust is slow to change &
	// with stronger long term effects
	Trust int32 `protobuf:"zigzag32,3,opt,name=Trust,proto3" json:"Trust,omitempty"`
	// Fear is a measure of how much the entity fears the other entity, fear is slow to change &
	// works as a counter to trust and a deterrent to aggression
	Fear int32 `protobuf:"zigzag32,4,opt,name=Fear,proto3" json:"Fear,omitempty"`
	// Affiliation is a measure of how much the entity is affiliated with the other entity, affiliation
	// has the same effects as trust, but is based on shared goals & obligation rat
	Affiliation int32 `protobuf:"zigzag32,5,opt,name=Affiliation,proto3" json:"Affiliation,omitempty"`
	// Most important events that have happened between the two entities.
	// nb. we keep only the most important recent events, others are assumed to be superseded
	// by more recent or powerful events.
	Memories []*Memory `protobuf:"bytes,6,rep,name=Memories,proto3" json:"Memories,omitempty"`
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *Relationship) GetID() *Metaref {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *Relationship) GetOpinion() int32 {
	if x != nil {
		return x.Opinion
	}
	return 0
}

func (x *Relationship) GetTrust() int32 {
	if x != nil {
		return x.Trust
	}
	return 0
}

func (x *Relationship) GetFear() int32 {
	if x != nil {
		return x.Fear
	}
	return 0
}

func (x *Relationship) GetAffiliation() int32 {
	if x != nil {
		return x.Affiliation
	}
	return 0
}

func (x *Relationship) GetMemories() []*Memory {
	if x != nil {
		return x.Memories
	}
	return nil
}

var File_relationship_proto protoreflect.FileDescriptor

var file_relationship_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x72, 0x65, 0x66, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x4f, 0x70, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x07,
	0x4f, 0x70, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x72, 0x75, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x54, 0x72, 0x75, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x46, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x46, 0x65, 0x61,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x11, 0x52, 0x0b, 0x41, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x08, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x08,
	0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x6b, 0x67, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relationship_proto_rawDescOnce sync.Once
	file_relationship_proto_rawDescData = file_relationship_proto_rawDesc
)

func file_relationship_proto_rawDescGZIP() []byte {
	file_relationship_proto_rawDescOnce.Do(func() {
		file_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(file_relationship_proto_rawDescData)
	})
	return file_relationship_proto_rawDescData
}

var file_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_relationship_proto_goTypes = []interface{}{
	(*Relationship)(nil), // 0: Relationship
	(*Metaref)(nil),      // 1: Metaref
	(*Memory)(nil),       // 2: Memory
}
var file_relationship_proto_depIdxs = []int32{
	1, // 0: Relationship.ID:type_name -> Metaref
	2, // 1: Relationship.Memories:type_name -> Memory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_relationship_proto_init() }
func file_relationship_proto_init() {
	if File_relationship_proto != nil {
		return
	}
	file_metadata_proto_init()
	file_memory_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_relationship_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Relationship); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relationship_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relationship_proto_goTypes,
		DependencyIndexes: file_relationship_proto_depIdxs,
		MessageInfos:      file_relationship_proto_msgTypes,
	}.Build()
	File_relationship_proto = out.File
	file_relationship_proto_rawDesc = nil
	file_relationship_proto_goTypes = nil
	file_relationship_proto_depIdxs = nil
}
