// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: research.proto

package structs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResearchTopic is something a faction can research
type ResearchTopic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the topic, must be unique amongst all topics
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Probability that the topic will be researched
	Probability float64 `protobuf:"fixed64,2,opt,name=Probability,proto3" json:"Probability,omitempty"`
	// Profession connected to researching this topic
	Profession string `protobuf:"bytes,3,opt,name=Profession,proto3" json:"Profession,omitempty"`
	// Ethos that this topic is connected to
	Ethos *Ethos `protobuf:"bytes,4,opt,name=Ethos,proto3" json:"Ethos,omitempty"`
}

func (x *ResearchTopic) Reset() {
	*x = ResearchTopic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_research_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResearchTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchTopic) ProtoMessage() {}

func (x *ResearchTopic) ProtoReflect() protoreflect.Message {
	mi := &file_research_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchTopic.ProtoReflect.Descriptor instead.
func (*ResearchTopic) Descriptor() ([]byte, []int) {
	return file_research_proto_rawDescGZIP(), []int{0}
}

func (x *ResearchTopic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResearchTopic) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *ResearchTopic) GetProfession() string {
	if x != nil {
		return x.Profession
	}
	return ""
}

func (x *ResearchTopic) GetEthos() *Ethos {
	if x != nil {
		return x.Ethos
	}
	return nil
}

var File_research_proto protoreflect.FileDescriptor

var file_research_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0b, 0x65, 0x74, 0x68, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01,
	0x0a, 0x0d, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x05, 0x45, 0x74, 0x68, 0x6f, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x74, 0x68, 0x6f, 0x73, 0x52, 0x05, 0x45, 0x74,
	0x68, 0x6f, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_research_proto_rawDescOnce sync.Once
	file_research_proto_rawDescData = file_research_proto_rawDesc
)

func file_research_proto_rawDescGZIP() []byte {
	file_research_proto_rawDescOnce.Do(func() {
		file_research_proto_rawDescData = protoimpl.X.CompressGZIP(file_research_proto_rawDescData)
	})
	return file_research_proto_rawDescData
}

var file_research_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_research_proto_goTypes = []interface{}{
	(*ResearchTopic)(nil), // 0: ResearchTopic
	(*Ethos)(nil),         // 1: Ethos
}
var file_research_proto_depIdxs = []int32{
	1, // 0: ResearchTopic.Ethos:type_name -> Ethos
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_research_proto_init() }
func file_research_proto_init() {
	if File_research_proto != nil {
		return
	}
	file_ethos_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_research_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResearchTopic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_research_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_research_proto_goTypes,
		DependencyIndexes: file_research_proto_depIdxs,
		MessageInfos:      file_research_proto_msgTypes,
	}.Build()
	File_research_proto = out.File
	file_research_proto_rawDesc = nil
	file_research_proto_goTypes = nil
	file_research_proto_depIdxs = nil
}
